# Generated by Django 5.0.2 on 2024-02-07 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='incident',
            options={'ordering': ['-created_on']},
        ),
    ]
