# Generated by Django 5.0.2 on 2024-02-13 21:02

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_alter_action_options_alter_incident_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('action_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='incidents.action')),
            ],
        ),
    ]
